version: '3.9'

secrets:
  apikey:
    file: ./secrets/apikey.txt
  secretkey:
    file: ./secrets/secretkey.txt

services:
  dynapork:
    image: hoodnoah/dynapork:latest
    secrets:
      - apikey
      - secretkey
    environment:
      - DOMAINNAME=domain.ext # The domain to manage
      - SUBDOMAIN=subdomain   # OPTIONAL: a subdomain, e.g. "vpn" to manage vpn.domain.ext
      - RECORDTYPE=A          # The record type to maintain
      - INTERVAL=300000       # The time between checks for a changed IP in milliseconds (there is an enforced minimum of 5 seconds, or 5000 milliseconds)
