name: Run Unit Tests
run-name: 🧪 Running unit tests
on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "develop"
      - "main"
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - run: dotnet build dynapork.sln
      - run: dotnet run --no-restore --project main/test
