name: GitHub Actions Demo
run-name: 🧪 Run classlib Expecto tests by ${{ github.actor }} ⚗️
on: 
  push:
    branches: 
      - 'main'
      - 'develop'
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'main/**'
      - 'develop/**'
    paths:
      - "**.fs"
      - "**.fsproj"
      - "**.sln"
      - ".github/workflows/**.yml"
    
jobs:
  Run-Unit-Tests:
    platform_matrix:
      strategy:
        matrix:
          platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ platform_matrix.platform }}
    steps:
      - run: echo "Checking out code from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Dotnet SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x
      - name: Install Dependencies
        run: |
          dotnet restore
      - name: Build
        run: |
          dotnet build
      - name: Run Expecto Tests Against Util Classlib
        run: |
          dotnet run --no-restore --project ./util/test/Util.Test.fsproj
      - run: |
          echo "Status: ${{ job.status }}."
