name: GitHub Actions Demo
run-name: 🧪 Run classlib Expecto tests by ${{ github.actor }} ⚗️
on: 
  push:
    branches: 
      - 'main'
      - 'develop'
  pull-request:
    types: [opened, synchronize]
    branches:
      - 'main/**'
      - 'develop/**'
    paths:
      - "**.fs"
      - "**.fsproj"
      - "**.sln"
    
jobs:
  Run-Unit-Tests:
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - run: echo "Checking out code from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Expecto Tests Against Util Classlib
        run: |
          dotnet run --project ./util/test/Util.Test.fsproj
      - run: echo "Status: ${{ job.status }}."
